[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "hulu"
version = "0.0.3"
description = "Client library to fine-tune and evaluate models on the HuLU benchmark."
readme = "README.md"
requires-python = ">=3.8"
license = { text = "Apache" }
authors = [
  { name = "ELTE Research Center for Linguistics", email = "varga.kristof@nytud.elte.hu" },
  { name = "ELTE Research Center for Linguistics", email = "osvath.matyas@nytud.elte.hu" }
]
keywords = [
  "artificial-intelligence",
  "machine-learning",
  "deep-learning",
  "natural-language-processing",
  "fine-tuning",
  "evaluation",
  "benchmark"
]
classifiers = [
  "Intended Audience :: Developers",
  "Intended Audience :: Education",
  "Intended Audience :: Science/Research",
  "License :: OSI Approved :: Apache Software License",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Topic :: Scientific/Engineering :: Artificial Intelligence"
]
dependencies = [
    "huggingface-hub",
    "datasets",
    "torch",
    "scikit-learn",
    "transformers",
    "accelerate",
    "numpy"
]

[project.urls]
Homepage = "https://hulu.nytud.hu/"
Repository = "https://github.com/nytud/HuLU"

[project.scripts]
hulu = "cli:cli"

[tool.setuptools]
package-dir = { "" = "src" }
